# Generated by Django 3.0.5 on 2020-04-08 02:20

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('apt', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=120)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
