# Generated by Django 3.0.5 on 2020-04-04 20:19

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):
    dependencies = [
        ('addresses', '0002_auto_20200404_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
