# Generated by Django 3.0.5 on 2020-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200505_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='servingareas',
            field=models.ManyToManyField(to='business.ServingAreas'),
        ),
    ]
