# Generated by Django 3.0.5 on 2020-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200505_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servingareas',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
