# Generated by Django 3.0.6 on 2020-05-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200427_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Store')),
            ],
        ),
    ]
