# Generated by Django 3.0.5 on 2020-05-05 15:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
            managers=[
                ('customer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='manageraccount',
            options={'verbose_name': 'Business Manager'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
