# Generated by Django 3.0.3 on 2020-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
