# Generated by Django 3.0.6 on 2020-05-04 17:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
            managers=[
                ('customer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='manageraccount',
            options={'verbose_name': 'Business Manager'},
        ),
    ]
