# Generated by Django 3.0.3 on 2020-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('services', models.CharField(max_length=2)),
                ('content', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
