# Generated by Django 3.0.5 on 2020-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
