# Generated by Django 3.0.5 on 2020-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0002_auto_20200407_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='services',
        ),
        migrations.AddField(
            model_name='feedback',
            name='store',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
