# Generated by Django 3.0.3 on 2020-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200228_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='services',
            field=models.CharField(choices=[('', 'Services'), ('LA', 'Laundry'), ('DC', 'Dry Cleaning')], max_length=2),
        ),
    ]
