# Generated by Django 3.0.3 on 2020-02-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200227_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='services',
            field=models.CharField(max_length=2),
        ),
    ]
