# Generated by Django 3.0.5 on 2020-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_auto_20200407_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='store',
            field=models.CharField(choices=[(1, 'bloomfield')], max_length=150),
        ),
    ]
