# Generated by Django 3.0.5 on 2020-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0004_auto_20200407_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='store',
            field=models.CharField(blank=True,
                                   choices=[(1, 'bloomfield'), (2, "Benny's Alligator Farm"), (3, 'Rust-eze')],
                                   max_length=150, null=True),
        ),
    ]
