# Generated by Django 3.0.5 on 2020-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20200407_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='store',
            field=models.CharField(blank=True, choices=[(1, 'bloomfield'), (2, "Benny's Alligator Farm"), (3, 'Rust-eze'), (4, 'myStore')], max_length=150, null=True),
        ),
    ]
