# Generated by Django 3.0.3 on 2020-03-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_adress',
            name='adress_order',
        ),
    ]
