# Generated by Django 3.0.3 on 2020-03-30 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dropoffDate',
            new_name='dropoff_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='pickupDate',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dropoffTime',
            new_name='dropoff_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickupTime',
            new_name='pickup_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceCost',
            new_name='service_cost',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceName',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceType',
            new_name='service_type',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='currentStatus',
            new_name='current_status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='deliveryStatus',
            new_name='delivery_status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='pickupStatus',
            new_name='pickup_status',
        ),
    ]
