# Generated by Django 3.0.3 on 2020-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20200330_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
    ]
