# Generated by Django 3.0.5 on 2020-04-08 01:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Laundry'), (2, 'Dry Cleaning'), (3, 'Elephants'), (4, 'Pizza Hunter'), (5, 'data'), (6, 'new')], max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('P', 'Processed'), ('PU', 'Picked up'), ('CL', 'Cleaning'), ('CP', 'Complete'), ('ER', 'Enroute'), ('D', 'Delivered'), ('C', 'Completed')], default='P', max_length=2),
        ),
    ]
