# Generated by Django 3.0.5 on 2020-04-04 20:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20200404_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(1, 'Laundry'), (2, 'Dry Cleaning'), (3, 'King Wash'), (4, 'Full Package'),
                         (5, 'Pizza Hunter'), (6, 'Fish Salesman'), (7, 'Dynomite Wash and Dry'),
                         (8, 'Goblin Cleaner Special'), (9, 'Specialty Wash'), (10, 'McQueen Speed Clean'),
                         (11, "WALL-E's Rust Off"), (12, "Morty's Magic Eraser")], max_length=26),
        ),
    ]
