# Generated by Django 3.0.5 on 2020-04-07 06:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20200407_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200),
        ),
    ]
